In [1]:
# Importing library
import numpy as np

In [2]:
# Function to input a matrix
def input_matrix(rows, cols, name):
    print(f"\nEnter elements for {name}:")
    matrix = []
    for i in range(rows):
        row = []
        for j in range(cols):
            while True:
                try:
                    val = float(input(f"Enter {name}[{i+1}][{j+1}]: "))
                    row.append(val)
                    break
                except ValueError:
                    print("Invalid input. Please enter a number.")
        matrix.append(row)
    return np.array(matrix)

In [3]:
# Function to display matrix
def display_matrix(matrix, name):
    print(f"\n{name}:")
    print(matrix)

In [6]:
# Function to show menu and get user choice
# =========================
def get_menu_choice():
    print("\n====== Matrix Operations Menu ======")
    print("1. Matrix Addition")
    print("2. Matrix Subtraction")
    print("3. Matrix Multiplication")
    print("4. Matrix Transpose")
    print("5. Matrix Determinant")
    while True:
        choice = input("Enter the number of the operation (1–5): ")
        if choice in ['1', '2', '3', '4', '5']:
            return choice
        else:
            print("Invalid choice. Please enter a number between 1 and 5.")

In [4]:
# Function to get matrix size
def get_matrix_size():
    print("\nSelect matrix size:")
    print("1. 2×2 Matrix")
    print("2. 3×3 Matrix")
    while True:
        size_choice = input("Enter 1 for 2×2 or 2 for 3×3: ")
        if size_choice == '1':
            return 2, 2
        elif size_choice == '2':
            return 3, 3
        else:
            print("Invalid choice. Please enter 1 or 2.")

In [10]:
# Main program loop
def main():
    print("Welcome to the Matrix Operations Tool!")

    while True:
        choice = get_menu_choice()
        rows, cols = get_matrix_size()
        A = input_matrix(rows, cols, "Matrix A")
        B = input_matrix(rows, cols, "Matrix B")

        display_matrix(A, "Matrix A")
        display_matrix(B, "Matrix B")

        print("\n========= RESULT =========")

        if choice == '1':
            result = np.add(A, B)
            print("Matrix Addition (A + B):\n", result)

        elif choice == '2':
            result = np.subtract(A, B)
            print("Matrix Subtraction (A - B):\n", result)

        elif choice == '3':
            result = np.dot(A, B)
            print("Matrix Multiplication (A × B):\n", result)

        elif choice == '4':
            print("Transpose of Matrix A:\n", A.T)
            print("Transpose of Matrix B:\n", B.T)

        elif choice == '5':
            if A.shape[0] == A.shape[1]:
                det_A = np.linalg.det(A)
                det_B = np.linalg.det(B)
                print("Determinant of Matrix A:", round(det_A, 2))
                print("Determinant of Matrix B:", round(det_B, 2))
            else:
                print("Determinant can only be calculated for square matrices.")

        again = input("\nDo you want to perform another operation? (Y/N): ").strip().lower()
        if again != 'y':
            print("Matrix operations completed.")
            break

In [11]:
# Run the program
if __name__ == "__main__":
    main()

Welcome to the Matrix Operations Tool!

====== Matrix Operations Menu ======
1. Matrix Addition
2. Matrix Subtraction
3. Matrix Multiplication
4. Matrix Transpose
5. Matrix Determinant
Enter the number of the operation (1–5): 3

Select matrix size:
1. 2×2 Matrix
2. 3×3 Matrix
Enter 1 for 2×2 or 2 for 3×3: 2

Enter elements for Matrix A:
Enter Matrix A[1][1]: 5
Enter Matrix A[1][2]: 10
Enter Matrix A[1][3]: 15
Enter Matrix A[2][1]: 20
Enter Matrix A[2][2]: 25
Enter Matrix A[2][3]: 30
Enter Matrix A[3][1]: 35
Enter Matrix A[3][2]: 40
Enter Matrix A[3][3]: 45

Enter elements for Matrix B:
Enter Matrix B[1][1]: 45
Enter Matrix B[1][2]: 40
Enter Matrix B[1][3]: 35
Enter Matrix B[2][1]: 30
Enter Matrix B[2][2]: 25
Enter Matrix B[2][3]: 20
Enter Matrix B[3][1]: 15
Enter Matrix B[3][2]: 10
Enter Matrix B[3][3]: 5

Matrix A:
[[ 5. 10. 15.]
 [20. 25. 30.]
 [35. 40. 45.]]

Matrix B:
[[45. 40. 35.]
 [30. 25. 20.]
 [15. 10.  5.]]

========= RESULT =========
Matrix Multiplication (A × B):
 [[ 750.  

## ✅ Conclusion

In this project, I built an interactive **Matrix Operations Tool** using Python and NumPy as part of my internship work. The tool allows users to perform basic matrix operations like **addition**, **subtraction**, **multiplication**, **transpose**, and **determinant** in a simple and structured way.

I designed it using a **menu-based interface** to make it more user-friendly, and added proper input checks and loops so users can run multiple operations without restarting the program each time. I also organized the code into **functions** to keep everything neat and manageable.

Through this project, I got more hands-on experience with:
- Writing clean, reusable Python functions
- Managing user input and avoiding common errors
- Using NumPy for performing matrix operations
- Focusing on user flow and interaction while coding

This task really helped me improve both my coding logic and confidence with Python — and it brought me one step closer to my goal of becoming a data scientist.